### ISSUE TITLE
Custom notes location

### ISSUE THREAD

**Issue by bogdan-calapod** [EdmondTabaku/eureka#2]
Hello and thank you for this nice plugin, works great as a small "scrapbook" instead of dealing with a separate buffer :D 

I noticed that every time I open Eureka it automatically creates a text file in the current directory. 

Is there any way to configure this to use a global folder instead ? Something like `/tmp/eureka/<cwd>/eureka-notes.txt`? 

Thanks again!

**Comment by EdmondTabaku** [comment]
Hello.

Glad you like it. 
Have you used the last version? 
We did fix the problem of the notes file.

Thanks!

**Comment by bogdan-calapod** [comment]
That was the problem - thanks, now it works perfectly!
